### ISSUE TITLE
Getting 400 Bad Request response from GraphQL server

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/FSharp.Data.GraphQL#251]
### Description

I'm trying to test the client provider with a local GraphQL server.  I'm trying a query that works fine using GraphiQL, but fails during runtime for the provider.

### Repro steps

Unfortunately I can't share the GraphQL server implementation, but I'll try to describe what happens.

Here's my program:

```fsharp
open FSharp.Data.GraphQL

type B = GraphQLProvider<"http://localhost:4000/graphql">

let op = B.Operation<"""
            query ($rId:Int) {
              answer(id: $rId) {
                id
                answer
              }
            } """>()

let result = op.Run(rId=74686)

[<EntryPoint>]
let main argv =
    printfn "The result is %A" result
    0 // return an integer exit code

```

It compiles without issue.  However, when I run it, I get the following:

```
Unhandled exception. System.TypeInitializationException: The type initializer for '<StartupCode$fsharp-test>.$Program' threw an exception.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at FSharp.Data.GraphQL.GraphQLClient.ensureSuccessCode@40-1.Invoke(HttpResponseMessage _arg1)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 417
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 882
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at Program.result@28-2.Invoke(Unit _arg4) in /Users/nat/Projects/fsharp-test/Program.fs:line 28
   at <StartupCode$fsharp-test>.$Program..cctor() in /Users/nat/Projects/fsharp-test/Program.fs:line 28
   --- End of inner exception stack trace ---
   at Program.main(String[] argv) in /Users/nat/Projects/fsharp-test/Program.fs:line 35
```

Here's what I'm running from GraphiQL:

```graphql
            query ($rId:Int) {
              answer(id: $rId) {
                id
                answer
              }
            }
```

is the query, and 

```json
{
"rId" : 74686
}
```

is the query variable.  I'm able to get a successful response back.

If I look at the log of my GraphQL server, I see the following:

```
// First set of logs is from client provider.
{ operationName: null,
  query:
   '($rId: Int) {\n  answer(id: $rId) {\n    id\n    answer\n    __typename\n  }\n  __typename\n}',
  variables: { rId: 74686 } }
{ host: 'localhost:4000',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '174' }

// Second set of logs is from using GraphiQL
{ query:
   '            query ($rId:Int) {\n              answer(id: $rId) {\n                id\n                answer\n              }\n            }',
  variables: { rId: 74686 } }
{ host: 'localhost:4000',
  'user-agent':
   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0',
  accept: 'application/json',
  'accept-language': 'en-US,en;q=0.5',
  'accept-encoding': 'gzip, deflate',
  referer: 'http://localhost:4000/graphiql',
  'content-type': 'application/json',
  origin: 'http://localhost:4000',
  'content-length': '178',
  dnt: '1',
  connection: 'keep-alive' }
```

Notice how the query appears to be really weirdly transformed.  If that's what the query is ending up as, I'm not surprised that it's failing.  Question is, why does it look so different from the GraphiQL query?

### Expected behavior

No runtime error should occur, the request should complete successfully.

### Actual behavior

400 Bad Request error occurs.

### Known workarounds

None.

### Related Information

Using the latest .NET SDK, and using version FSharp.Data.GraphQL.Client v1.0.2.

**Comment by johnberzy-bazinga** [comment]
@NatElkins I think I see what's going on here. We actually parse the query, augment it with the addition of the `__typename` field and then rewrite the query. This is so we know what to serialize the responses to (in the case of a union or interface return type). It looks like when we rewrite the query and the query has variables but has no name we mistake the lack of name for a shorthand query. We should check that no name and no variables are present before rewriting to the shorthand syntax. Can you try adding a name (e.g. `query MyQuery ($var1)...`) to see if the problem still persists?

**Comment by NatElkins** [comment]
Yup changing it to `query q ...` works now.  Thanks!

**Comment by johnberzy-bazinga** [comment]
The client should be working with shorthand queries now.
